CREATE TABLE HELLOWORLD (
   HELLO VARCHAR(15),
   WORLD VARCHAR(15),
   DIALECT VARCHAR(15) NOT NULL,
   PRIMARY KEY (DIALECT)
);

CREATE TABLE USERACCOUNT (
	EMAIL		VARCHAR(50) NOT NULL,
	FIRSTNAME	VARCHAR(20) NOT NULL,
	LASTNAME	VARCHAR(10) NOT NULL,
	LASTLOGIN	BIGINT,
	DIALECT	VARCHAR(10)
);

CREATE TABLE TEST (
	A INT NOT NULL,
	B INT,
	PRIMARY KEY(A)
);